language: objective-c
osx_image: xcode9.2

branches:
  only:
   - master
cache:
- bundler
- cocoapods

before_install:
- bundle update
- bundle install
- pod repo update

script:
- bundle exec fastlane test

after_success:
  - bash <(curl -s https://codecov.io/bash)
