require 'yaml'

default_platform(:ios)

lane :oss_keys do
  keys = ['PlayAPIToken',
    'PlayAPIKey']

  commands = keys.map { |key|
    command = "bundle exec pod keys set #{key} '-' Play"

    command
  }.join(' ; ')

  sh "cd .. ; #{commands}"
end

desc "Set all the API keys required for run"
lane :oss do
  oss_keys

  cocoapods
end

desc "Increment major version"
lane :major do 
 version_number = update_version_number_and_commit(bump_type:"major")
 version_number
end

  desc "Runs all the tests on an iPhone"
  lane :test do
     scan(scheme: "Play")
    slather(
      output_directory: "coverage",
      workspace: "Play.xcworkspace",
      scheme: "Play",
      proj: "Play.xcodeproj",
      html: true,
	ignore: [
        "**/Storyboard.swift",
        "**/PlayAPI.swift",
        "**/ModalTransition.swift",
	"**/Helperfunctions.swift",
        "**/UIImageView+Kingfisher.swift"	
      ]
    )
  end

desc "Release a new beta version on ITC"
desc "This action does the following:"
desc ""
desc "- Verifies API keys are non-empty"
desc "- Ensures a clean git status"
desc "- Increment the build number"
desc "- Commit and push the version bump"
lane :deploy do |options|
  ensure_git_branch
  ensure_git_status_clean
  ensure_git_in_sync

  version = options[:version]
  raise "You must specify a version in A.B.X format to deploy." if version.nil? || version.scan(/\d+\.\d+\.\d+/).length == 0


  # Increment build number to current date
  build_number = Time.new.strftime("%Y.%m.%d")
  increment_build_number build_number: build_number

  # Generate release notes from CHANGELOG
  changelog_filename = '../CHANGELOG.yml'
  changelog_yaml = YAML.load_file(changelog_filename)
  release_notes = changelog_yaml['upcoming'].map{ |note| note.prepend '- ' }.join("\n")

  # Increment to the specified version number
  increment_version_number version_number: version

  # Add a changelog entry for this version

  changelog_contents = File.read(changelog_filename)
  existing_releases = changelog_contents.split('releases:').last
  this_release = changelog_yaml['upcoming'].map{ |note| note.prepend '  ' }.join("\n")
  changelog_contents = <<-EOS
upcoming:

releases:
- version: #{version}
  date: #{Time.new.strftime("%B %d %Y")}
  notes:
#{this_release}
#{existing_releases}
EOS

  File.open(changelog_filename, 'w') { |file| file.puts changelog_contents }


  # Check for the necessary provisioning profile and download it from the developer portal if necessary.
  sigh(
    output_path: "/tmp",
    app_identifier: "br.com.douglast.jobs.Play"
  )

  # Use the UDID of the newly created provisioning profile.
  # The Xcode project is configured to read the provision profile UUID through this environmental variable.
  # See here for more information: https://github.com/fastlane/fastlane/blob/master/docs/CodeSigning.md#deprecated-using-environment-variables
  ENV["PROFILE_UDID"] = lane_context[SharedValues::SIGH_UDID]

  # Generate a name for the xcarchive file.
  # Also generate the destination path which is inside the Timehop dropbox folder.
  archive_name = version + " - Play " + Time.now.strftime("%F %H.%M.%S") + ".xcarchive"
  archive_path = archive_destination(archive_name)

  # Build the app.
  gym(
    workspace: "Play.xcworkspace",
    configuration: "Release",
    scheme: "Play",
    clean: false,
    codesigning_identity: "iPhone Distribution: DOUGLAST ",
    archive_path: archive_path,
    use_legacy_build_api: true # There's a bug in the new Xcode 7 API that causes problems. This forces use of the old API.
  )

  # Upload the build to iTunes Connect.
  deliver(
    force: true,
    skip_screenshots: true
  )

  clean_build_artifacts

  # Tag release and push to GitHub
  sh "git add .. ; git commit -m 'Deploying version #{version}.'" # Can't use commit_version_bump to include changelog changes
  add_git_tag tag: version
  push_to_git_remote
end


desc "Release a new beta version on ITC"
desc "This action does the following:"
desc ""
desc "- Ensures a clean git status"
desc "- Increment the build number"
desc "- Commit and push the version bump"
desc "Deploy a new version to the App Store"
lane :appstore do
  ensure_git_branch
  ensure_git_status_clean
  ensure_git_in_sync

  cocoapods

  # Ask for a new CFBundleShortVersionString and bump the CFBundleVersion.
  new_build_number = next_version
  version = ask("Enter a new version number: ")
  set_build_number(
    new_build_number
  )
  set_version_number(
    version
  )

   # version = options[:version]
  #raise "You must specify a version in A.B.X format to deploy." if version.nil? || version.scan(/\d+\.\d+\.\d+/).length == 0

  # Check for the necessary provisioning profile and download it from the developer portal if necessary.
  sigh(
    output_path: "/tmp",
    app_identifier: "br.com.douglast.jobs.Play"
  )

  # Use the UDID of the newly created provisioning profile.
  # The Xcode project is configured to read the provision profile UUID through this environmental variable.
  # See here for more information: https://github.com/fastlane/fastlane/blob/master/docs/CodeSigning.md#deprecated-using-environment-variables
  ENV["PROFILE_UDID"] = lane_context[SharedValues::SIGH_UDID]

  # Generate a name for the xcarchive file.
  # Also generate the destination path which is inside the Timehop dropbox folder.
  archive_name = version + " - Play " + Time.now.strftime("%F %H.%M.%S") + ".xcarchive"
  archive_path = archive_destination(archive_name)

  # Build the app.
  gym(
    workspace: "Play.xcworkspace",
    configuration: "Release",
    scheme: "Play",
    clean: false,
    codesigning_identity: "iPhone Distribution: DOUGLAST ",
    archive_path: archive_path,
    use_legacy_build_api: true # There's a bug in the new Xcode 7 API that causes problems. This forces use of the old API.
  )

  # Upload the build to iTunes Connect.
  deliver(
    force: true,
    skip_screenshots: true
  )

  clean_build_artifacts

  commit_version_bump(
    message: "Version bump " + version + ", " + new_build_number,
    force: true
  )

  push_to_git_remote
end

  error do |lane, exception|
  if lane == :deploy
    puts "Unable to deploy, removing build artefacts."
    clean_build_artifacts
  end
end
