# This file contains the fastlane.tools configuration
# You can find the documentation at https://docs.fastlane.tools
#
# For a list of all available actions, check out
#
#     https://docs.fastlane.tools/actions
#

# Uncomment the line if you want fastlane to automatically update itself
# update_fastlane

default_platform(:ios)

platform :ios do
  desc "Description of what the lane does"
  lane :custom_lane do
    # add actions here: https://docs.fastlane.tools/actions
  end

  desc "Runs all the tests"
  lane :test do
     scan(scheme: "Play")
    slather(
      output_directory: "coverage",
      workspace: "Play.xcworkspace",
      scheme: "Play",
      proj: "Play.xcodeproj",
      html: true,
	ignore: [
        "**/Storyboard.swift",
        "**/PlayAPI.swift",
        "**/ModalTransition.swift",
	"**/Helperfunctions.swift",
        "**/UIImageView+Kingfisher.swift"	
      ]
    )
  end
end
